const express = require('express');
const router = express.Router();
const db = require('../db');

// Update portfolio settings
router.put('/:id', async (req, res, next) => {
  try {
    const { id } = req.params;
    const { portfolio } = req.body;

    const profile = await db.profiles.findById(id);
    if (!profile) {
      return res.status(404).json({ error: true, message: 'Profile not found' });
    }

    profile.portfolio = { ...profile.portfolio, ...portfolio };
    await db.profiles.save(profile);

    res.json({
      success: true,
      message: 'Portfolio customized successfully',
      portfolio: profile.portfolio
    });
  } catch (error) {
    next(error);
  }
});

// One-Click Vercel Deployment Simulation with live-style build logs
router.post('/:id/deploy', async (req, res, next) => {
  try {
    const { id } = req.params;
    const { vercelSubdomain } = req.body;

    const profile = await db.profiles.findById(id);
    if (!profile) {
      return res.status(404).json({ error: true, message: 'Profile not found' });
    }

    const subdomain = vercelSubdomain || profile.githubUsername.toLowerCase();
    
    // Simulate real logs
    const logs = [
      `[10:14:02] 📦 Cloning repository github.com/${profile.githubUsername}/${subdomain}-portfolio...`,
      `[10:14:05] ⚙️ Resolving project structure and dependencies...`,
      `[10:14:08] 📥 Installed: React 19, TypeScript 5, Tailwind CSS 4, Framer Motion 11`,
      `[10:14:11] 🚀 Building production bundle...`,
      `[10:14:14] 📊 Optimized chunks successfully compiled (452KB total size)`,
      `[10:14:16] ☁️ Deploying serverless edge routines and rendering routes...`,
      `[10:14:18] 🔒 Securing SSL certificates for custom domain...`,
      `[10:14:20] 🎉 Deployment Successful! Active on Edge Servers.`
    ];

    // Save deployed parameters
    profile.portfolio = {
      ...profile.portfolio,
      deployedUrl: `https://${subdomain}.vercel.app`,
      vercelSubdomain: subdomain,
      deployedAt: new Date().toISOString()
    };
    await db.profiles.save(profile);

    res.json({
      success: true,
      message: 'Deployment triggered successfully',
      logs: logs,
      deployedUrl: profile.portfolio.deployedUrl
    });

  } catch (error) {
    next(error);
  }
});

// GitHub push code sync simulation
router.post('/:id/push-repo', async (req, res, next) => {
  try {
    const { id } = req.params;
    const { repositoryName } = req.body;

    const profile = await db.profiles.findById(id);
    if (!profile) {
      return res.status(404).json({ error: true, message: 'Profile not found' });
    }

    const repoName = repositoryName || `${profile.githubUsername.toLowerCase()}-portfolio-v4`;

    const logs = [
      `[10:15:00] 🔍 Authenticating GitHub OAuth tokens...`,
      `[10:15:02] 📦 Initializing local Git staging tree...`,
      `[10:15:03] ➕ Added: src/components, tailwind.config.js, index.html`,
      `[10:15:05] 💾 Committing: "feat: initial portfolio code generated by DevForge AI"`,
      `[10:15:07] 🔗 Establishing remote origin: github.com/${profile.githubUsername}/${repoName}`,
      `[10:15:09] 📤 Pushing commit trees to master branch...`,
      `[10:15:11] ✅ Repository synced successfully. Codebase live at github.com/${profile.githubUsername}/${repoName}`
    ];

    res.json({
      success: true,
      message: 'Code pushed to GitHub repository',
      logs: logs
    });

  } catch (error) {
    next(error);
  }
});

// Public route to fetch a user's portfolio by username
router.get('/public/:username', async (req, res, next) => {
  try {
    const { username } = req.params;
    
    // Find profile by githubUsername
    const profile = await db.profiles.findByGithub(username);
    if (!profile) {
      return res.status(404).json({ error: true, message: 'Portfolio not found' });
    }

    res.json({
      success: true,
      profile: profile
    });
  } catch (error) {
    next(error);
  }
});

module.exports = router;
